lenguage: generic

services:
  - docker

after_success:
  - docker build -t simon3640/siga-backend -f ./backend/Dockerfile.prod ./backend

  - docker build -t simon3640/siga-client -f ./client/Dockerfile.prod ./client

  - docker build -t simon3640/siga-nginx -f ./nginx/Dockerfile.prod ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push simon3640/siga-backend

  - docker push simon3640/siga-client

  - docker push simon3640/siga-nginx

  slack: $SLACK_NAME:$SLACK_TOKEN
  on_success: always
  on_failure: always

deploy:
  provider: script
  script: ls