lenguage: generic

services:
  - docker

after_success:
  - docker build -t simon3640/siga-backend -f ./backend/Dockerfile.prod ./backend

  - docker build -t simon3640/siga-client -f ./client/Dockerfile.prod ./client

  - docker build -t simon3640/siga-nginx -f ./nginx/Dockerfile.prod ./nginx

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push simon3640/siga

deploy:
  provider: elasticbeanstalk
  region: sa-east-1
  app: siga
  env: Siga-env
  access_key_id: $AWS_ACCESS_KEY_ID
  secred_access_key: $AWS_ACCESS_SECRET_KEY
  bucket_name: "siga-bucket-develop"
  bucket_path: "docker"
  on:
    branch: main