lenguage: generic
services:
  - docker  
after_success:
  - docker build -t simon3640/siga-backend -f ./backend/Dockerfile.prod ./backend
  - docker build -t simon3640/siga-client -f ./client/Dockerfile.prod ./client
  - docker build -t simon3640/siga-nginx -f ./nginx/Dockerfile.prod ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push simon3640/siga-backend
  - docker push simon3640/siga-client
  - docker push simon3640/siga-nginx
  

notifications:
  slack: $SLACK_NAME:$SLACK_TOKEN

deploy:
  provider: script
  script: ssh -i ./Siga-brasil.pem ubuntu@18.228.135.12  bash deploy.sh
  on:
    branches: main

before_install:
  - openssl aes-256-cbc -K $encrypted_f19bd43112f0_key -iv $encrypted_f19bd43112f0_iv
    -in Siga-brasil.pem.enc -out Siga-brasil.pem -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./Siga-brasil.pem
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./Siga-brasil.pem