from .applications.commission import commission_resolution_generation
from .applications.permission import permission_resolution_generation
from .applications.initial_letter import initial_letter_generation
from .applications.full_time import fill_vice_document
from .applications.work_plan import fill_work_plan_format

from .applications.hour_aval_letter import hour_aval_letter_generation
from .applications.hour_aval_act import hour_aval_act_generation