from .applications.commission import commission_resolution_generation
from .applications.permission import permission_resolution_generation
from .applications.initial_letter import initial_letter_generation