from datetime import datetime

from app.domain import schemas

init_holiday: list[schemas.HolidayCreate] = [
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 1, 1)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 1, 9)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 3, 20)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 4, 6)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 4, 7)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 5, 1)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 5, 22)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 6, 12)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 6, 19)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 7, 3)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 7, 20)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 8, 7)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 8, 21)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 10, 16)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 11, 6)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 11, 13)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 12, 8)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2023, 12, 25)),

    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 1, 1)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 1, 8)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 3, 25)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 3, 28)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 3, 29)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 5, 1)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 5, 13)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 6, 3)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 6, 10)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 7, 1)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 7, 20)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 8, 7)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 8, 19)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 10, 14)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 11, 4)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 11, 11)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 12, 8)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2024, 12, 25)),

    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 1, 1)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 1, 6)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 3, 24)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 4, 17)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 4, 18)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 5, 1)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 6, 2)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 6, 23)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 6, 30)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 7, 20)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 8, 7)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 8, 18)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 10, 13)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 11, 3)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 11, 17)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 12, 8)),
    schemas.HolidayCreate(holiday_date=datetime.datetime(2025, 12, 25)),
]
