from .user import User
from .department import Department
from .school import School
from .rol import Rol
from .state import State
from .application import Application
from .application_type import ApplicationType
from .application_subtype import ApplicationSubType
from .application_state import Application_state