name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
    - shell: bash
      env: 
        DOCKER_ID: ${{ secrets.DOCKER_ID }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    - run: | 
      docker build -t simon3640/siga-nginx -f ./nginx/Dockerfile.prod ./nginx
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      docker push simon3640/siga-nginx
